### ISSUE TITLE
kafka-ch-dispatcher has no ownerref

### ISSUE THREAD

**Issue by AceHack** [knative/eventing-contrib#1188]
Describe the bug
kafka-ch-dispatcher gets created as needed but without a ownerref, this causes problems on uninstall of eventing as the kafka-ch-dispatcher deployment never gets cleaned up and is left around as an orphan crash loop forever.

Expected behavior
kafka-ch-dispatcher to get cleaned up on uninstall of knative Kafka channel controller.

To Reproduce
Install knative Kafka channel controller
Create a kafka channel
Delete a Kafka channel
Uninstall knative Kafka channel controller

Knative release version
0.14.1

Related issue
https://github.com/knative/eventing/issues/3035

**Comment by aliok** [comment]
This will be only solved for the cluster scoped dispatcher.

The namespaced dispatcher won't still have an "OwnerRef" because the strategy here is to create the dispatcher in advance with an ownerRef. The namespace dispatchers need to be created later and we there's nothing that can be set as the ownerRef. If it was per channel, instead of per namespace, we would be able to set the CR instance as the owner.

Related: https://github.com/knative/eventing-contrib/issues/1524

**Comment by aliok** [comment]
Oh boy... Can't create the dispatcher `service` in advance... The thing is, the `type` should be set to `ExternalName` but that requires the `externalName` to be set to. And in the code, we set it to `fmt.Sprintf("%s.%s.svc.%s", dispatcherName, testNS, utils.GetClusterDomainName())` which cannot be done in the YAML.

Another approach would be creating the `service` in advance with another `type` and then change it in the reconciliation. But, once the `service` is set up like that, we cannot update the service.

@lionelvillard @slinkydeveloper @vaikas any suggestions?

BTW, there are 2 kinds of `dispatchers`:
1. Cluster scoped dispatchers
2. Namepaced dispatchers

This I was only attempting to fix the 1st one's ownerRef by setting it to the `KnativeEventing` CR in the operator.
For the 2nd one, there's nothing available as the ownerRef. Instead of dispatcher per namespace, we can actually do dispatcher per channel CR, which would allow us to set the channel CR as the ownerRef.

I need feedback.

**Comment by matzew** [comment]
sounds messy... :thinking:

**Comment by slinkydeveloper** [comment]
Ok maybe it's me, but i didn't properly get what's the problem here. @aliok the dispatcher is brought up by the controller right? So could the owner ref be just the controller?

**Comment by aliok** [comment]
Don't know. Could work I guess. Let me think about that.

**Comment by lionelvillard** [comment]
we tried setting the owner ref to be the controller using the downward API without success (problem with the uid if I recall well).

**Comment by aliok** [comment]
For reference: 
These 2 comments explain why the controller can't be used as the owner:
- https://github.com/knative/eventing/pull/3040#discussion_r423177564
- https://github.com/knative/eventing/pull/3040#pullrequestreview-409360520
(thanks @pierDipi for clarification)

Can't come up with any alternatives to set as the owner.

**Comment by aliok** [comment]
> Oh boy... Can't create the dispatcher service in advance... The thing is, the type should be set to ExternalName but that requires the externalName to be set to. And in the code, we set it to fmt.Sprintf("%s.%s.svc.%s", dispatcherName, testNS, utils.GetClusterDomainName()) which cannot be done in the YAML.

My bad... I don't think this is accurate: `externalName` is not needed.
Reworking a PR now.

**Comment by aliok** [comment]
Reworked PR: https://github.com/knative/eventing-contrib/pull/1536

**Comment by vaikas** [comment]
For the namespaced one, using the ownerref of the channel seems reasonable to me. The only caveat is that do we really want there to be 1:1 mapping between a channel and a dispatcher?
For the cluster one, if it's the problem getting the UID, can't we just ask the API server who am I and get the UID?

**Comment by aliok** [comment]
> For the namespaced one, using the ownerref of the channel seems reasonable to me. The only caveat is that do we really want there to be 1:1 mapping between a channel and a dispatcher?

Won't work if there's more than 1 channel in a namespace.

> For the cluster one, if it's the problem getting the UID, can't we just ask the API server who am I and get the UID?

I think this will be fine now, with the PR: https://github.com/knative/eventing-contrib/pull/1536

**Comment by AceHack** [comment]
We have more than one channel per namespace.  Will this fix my issue?

**Comment by lionelvillard** [comment]
@AceHack Are you using the hidden `eventing.knative.dev/scope` annotation?

**Comment by AceHack** [comment]
I didn't think it was hidden, it's called out here in the docs.
https://github.com/knative/eventing-contrib/tree/master/kafka/channel#namespace-dispatchers

And yes we are using that

**Comment by lionelvillard** [comment]
thanks @AceHack. Can I ask you a couple more questions: 
- Are you also using the cluster dispatcher?
- If the answer is no, would you be ok if instead of the annotation we provide a release artifact that only includes the namespace dispatcher?

thanks.

**Comment by AceHack** [comment]
Currently, we are also using the cluster dispatcher but we could avoid it, it's not absolutely necessary.  It's some more works for us to deploy the namespace dispatcher separately but something we could do.

**Comment by AceHack** [comment]
We have multiple kafka clusters and need the ability to connect to the different ones per namespace

**Comment by lionelvillard** [comment]
thanks @AceHack, this is very helpful!

**Comment by AceHack** [comment]
We actually would like to connect to different ones per topic, but we've been getting by with per namespace.

**Comment by lionelvillard** [comment]
@matzew @slinkydeveloper @lberk

**Comment by aliok** [comment]
@AceHack 

> We have more than one channel per namespace. Will this fix my issue?

No, in the fix PR, only the cluster scope dispatcher is created in advance.

For the namespaced ones nothing changed.

**Comment by aliok** [comment]
> We actually would like to connect to different ones per topic, but we've been getting by with per namespace.

IMO we should have all these information in the CR: cluster, topic, etc
