### ISSUE TITLE
[Question] Any suggestions on building channel from scratch

### ISSUE THREAD

**Issue by Yiyiyimu** [knative/eventing-contrib#1370]
Hi community,

I'm trying to build channel backed by [Apache RocketMQ](https://github.com/apache/rocketmq), a kafka-like MQ. Since I could not found documentation or samples on channel building like source have, right now I'm reading implementation of Kafka channel and try to figure out something. I would appreciate it if someone could give me some advice on building channel.

**Comment by Yiyiyimu** [comment]
@matzew Hi Matthias! Do you have some suggestions?

**Comment by aliok** [comment]
cc @slinkydeveloper @pierDipi

**Comment by slinkydeveloper** [comment]
Hi @Yiyiyimu my GSoC student @pierDipi is building from scratch a broker for Kafka mixin Java and Golang. It's a pretty neat project and you could be inspired by it if you're trying to create a multi/language project. Here is the link (it's a WIP): https://github.com/knative-sandbox/eventing-kafka-broker

Otherwise, the best way to start atm is to grab the https://github.com/knative-sandbox/sample-controller (which gives you a well defined project skeleton) to scaffold the project, then take as reference the kafka channel implementation: https://github.com/knative/eventing-contrib/tree/master/kafka/channel

**Comment by pierDipi** [comment]
Key points to get started:

- This is the main: https://github.com/knative/eventing-contrib/blob/master/kafka/channel/cmd/channel_controller/main.go
  - `controller.NewController` function is defined by the channel implementor and it's responsible for pulling `Reconciler`'s dependencies (see [Knative injection](https://github.com/knative/pkg/tree/master/injection)) and registering resource handlers. (see https://github.com/knative/eventing-contrib/blob/master/kafka/channel/pkg/reconciler/controller/controller.go)
- Read carefully [Knative injection and code generation](https://github.com/knative/pkg/tree/master/injection).
- Write a `ReconcileKind(ctx, <your_resource>)`. In this method, we react to resources created/updated. (see https://github.com/knative/eventing-contrib/blob/master/kafka/channel/pkg/reconciler/controller/kafkachannel.go#L142)

Hope this helps!

**Comment by Yiyiyimu** [comment]
Thank you @slinkydeveloper @pierDipi for your suggestions! They're really detailed and feasible.

The project is so attractive to me and there must be a lot of aspects that I could use. Can't wait to see it coming!
