### ISSUE TITLE
Provide option for configuring offset number in kafka source

### ISSUE THREAD

**Issue by itsmurugappan** [knative/eventing-contrib#1492]
**Problem**
Currently the kafka source starts from the latest offset. There might be scenarios where the user might need to specify earliest offset or a specific offset number. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Developer

**Exit Criteria**
User is able to specify offset number while creating the kafka source

**Comment by aliok** [comment]
Could be relevant: https://github.com/knative/eventing-contrib/issues/655

**Comment by aliok** [comment]
@itsmurugappan 

What is the specific use case here? We (@slinkydeveloper and I) are trying to understand if this is a rare case that perhaps we should handle differently.

The problematic situation happens when using the offset when consumer group is defined vs not defined.

**Comment by itsmurugappan** [comment]
There are cases where people would want to retry specific transactions that may already have been processed.

**Comment by slinkydeveloper** [comment]
> There are cases where people would want to retry specific transactions that may already have been processed.

Are you trying to handle kafka transactions with kafka source? Perhaps KafkaSource is not the right tool for that.

> In those scenarios it will be really handy if we could choose the starting point.

I'm particularly concerned about this feature, both on the spec side and the implementation side:

* What happens if a consumer group already exists, say with offset 100, but the user configures in kafka source an offset, say 200?
* What happens if, similar to above, the user doesn't configure the offset first, then updates the kafka source cr and configures the offset with a value higher than the actual processing status?
* Should the KafkaSource continue to commit the offset when the initial offset is already configured?
* KafkaSource spec fields ultimately are "templates" of the resource pods, what happens if we implement a scalable kafka source? Every instance should restart from that offset? Also note that this one might even create loops, because every time it would reset the consumer group state
* Similar to above, what happens if the kafkasource crashes and then restarts? Should it restart from the configured offset?
* Should the offset and consumer group be exclusive fields, to avoid any of the above problems? But what if the user wants to set both the consumer group and the offset (which is reasonable if the consumer group does not exists)?
* How do we communicate to the user such edge cases?

I wonder, would it makes sense for you to create the consumer group by hand, with the fixed offset you want, and **then** create the kafka source specifying your custom consumer group name? There are different CLI tools out there to do so.

**Comment by itsmurugappan** [comment]
I wasnt talking about kafka transaction, i meant regular kafka messages, sorry for the wording there. We have faced scenarios where we had to reprocess some messages. That was my usecase. 

I acknowledge your concerns. Writing a one of consumer for this purpose would make more sense. Thank you!

**Comment by itsmurugappan** [comment]
I have few other use cases for this request, since i closed it here, creating a issue in the new repo -> https://github.com/knative-sandbox/eventing-kafka/issues/289
