### ISSUE TITLE
Using RabbitMQ as a event source

### ISSUE THREAD

**Issue by Justin2997** [knative/eventing-contrib#210]
## Expected Behavior
I create these issues to start a work in progress that I plan to work on. We will have a list of events on one or more queue in RabbitMQ. Those events will flow to the respective pod in Knative. I was planning to do something like the AWS SQS event source.

My gold is to use RabbitMQ to send data from one pod to another and externally feed the queue.

## Additional Info
I work with Knative for 1 month and I am now to the DevOps work. Feel free to help me or ask questions if there is.

**Comment by Justin2997** [comment]
WIP : https://github.com/Justin2997/knative-rabbitmq-to-lambda-source

**Comment by evankanderson** [comment]
/kind feature-request

Thanks for letting us know! A few tips to make the process smooth:

* Please prepare these to go into `contrib` with a separate yaml install.
* In the future, we may end up creating OWNERS for each directory matching `contrib/*` so that each contributed system has specific maintainers.

**Comment by daisy-ycguo** [comment]
I'm co-work with @Justin2997 on this issue. The latest progress can be check in the master branch of this repo: https://github.com/Justin2997/eventing-sources.

**Comment by Justin2997** [comment]
PR open here : https://github.com/knative/eventing-sources/pull/336

**Comment by Justin2997** [comment]
Closing because the source is present at : https://github.com/knative-sandbox/eventing-rabbitmq/tree/master/source
