### ISSUE TITLE
Eventing Sources framework/API

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#343]
## Expected Behavior

It should be really simple to write sources. Ideally a source author would have not much to deal with the "infrastructure" that runs the source (e.g. kubebuilder).

Ideally a author would provide some arguments that are manifested in the CRD, and will be provided as config object to some handler, that implements a simple lifecycle.

The lifecycle would offer the author to perform _his_ domain knowledge:
* establish connection to 3rd party system
* consume and return messages as "cloudevents"
* tear down the established connection

The author should not have to write "CloudEvent" API or perform any of the protocol (currently HTTP) invocations that gets the messages/events (as CloudEvents) to the sink.

The framework itself - if possible - might do that: do a POST of the CloudEvent to the sink, and do proper `ACK` or `NACK` of the message, or send a meaningful HTTP error to the 3rd party system (e.g. when the system is webhook based)

## Actual Behavior

Different sources, do similar slightly different, and sometimes not correct.

see for some background:
* https://github.com/knative/eventing-sources/issues/304
* https://github.com/knative/eventing-sources/issues/342
* https://github.com/knative/eventing-sources/issues/332

**Comment by matzew** [comment]
Possible API for such a handler:

```go
type EventingSourceHandler interface {
	// Setup is run at the beginning of a new session.
	Setup(Config) error

	// Cleanup is run at the end of a session, once all Consume()s have exited.
	Cleanup() error

	// Start a consumer logic to receive/poll messages and return each as CloudEvent.
	Consume() (CloudEvent, error)
}
```

```

**Comment by alanconway** [comment]
I did some prototyping of this at

https://github.com/alanconway/lightning

I came at this from the messaging perspective: how to reduce duplication and minimise effort to build AMQP an MQTT event transports. I was quite ignorant of knative at time of writing, it needs a total rewrite to fit with established CNCF and knative APIs. However if you ignore the packaging, terminology and duplication, I think there are some good ideas:

pluggable event "formats" - JSON is not a special case, all event formats are looked up by event-message format media type. This is completely independent of the transport.
separate abstractions for "Event" (should be using the CNCF stuff here) and "Message". A Message contains an event, it is implemented by a transport but it has a generic API so you can write code that transfers messages between different transports, without any knowledge of the transport implementations.
simple interfaces for transport implementations - I call these lightning.Source an lightning.Sink, the names are bad as they clash with the knative meaning, but the concept is valid - a generic API to get and put messages from different transports in a single executable.
freely combine arbitrary transports - not just X to HTTP but X to Y. Clearly HTTP is an important case, but not a special one. I can build an AMQP-MQTT direct event bridge, or a multi-transport event channel that allows run-time transport plug-ins to be added. I started work on something like this, it's not in the prototype yet.
An important aspect that's not in the prototype yet (I have done some work on it) is  an abstraction for "acknowledgement" or "completion" of event delivery. Different transports have different options, but you can boil it down to 3 basic qualities of service:

"at most once" aka "unreliable":  delivery can fail without notice
"at least once": delivery success is acknowledged, sender must replay on failure to get reliability. "Failure" can be a definite error response, a connection failure or timeout on ack. Duplicates can occur since timeout or connection failure does not prove the event was not delivered but the sender must replay in case it wasnt.
"exactly once": sender gets a definite success/fail response. This requires persistent storage for sender and receiver to reconcile after a process crash or restart.
MQTT calls these levels 0, 1 and 2 which is nice and succinct  API wise it's not as hard as it might sound - you need the event Message abstraction to have a "Completed(error)" call an you need something to deal with persistence for qos 3. This could be as simple as some kind of "GetStore() (id string); UseStore(id string)" if the transport does the work, maybe a little more complex if the generic code needs full control of where the transport stores it's in-flight message log.

I'm very interested in contributing here, I'll read https://github.com/knative/eventing-sources/issues/343 and try to put some initial ideas together for review.

**Comment by aslom** [comment]
That would help with developer experience especially consistency in configurations for example
https://github.com/knative/eventing-sources/issues/339

**Comment by vaikas-google** [comment]
This is definitely something that's timely as we've now done quite a few of these as a community, so we've learned quite a few patterns and as usual, it's best to abstract those patterns. I'm personally very interested in this area, so yay!
I view there being roughly 3 areas that are typically required for a given source. Some of these don't apply in all cases, but roughly these buckets imho need to be considered:

 1. Subscription Schema - Need a definition of what is required to establish the subscription. This typically means credentials and definition of how to specify what's being subscribed to. A user should be able to get this information by inspecting the Source (in the case of a CRD, this for example is done by specifying the OpenAPI description as part of the) and not require going OOB. When a source is a CRD (operator pattern), this is fairly easy to do. For existing Container Sources this is not the case, so something to keep in mind.

 2. Control Plane - Need to run some code on the cluster to establish the data plane, which is the job of the Controller in the Operator based model. This also handles the Reconcile in case there are changes made to the specific configuration of the source. These are obviously going to have to be custom for each different Source. So, here we need to talk to the "authoritative source" and set up the subscription for events _and_ establish the data plane. Naively these fall into two categories: Push / Pull.

 3. Data Plane - This is the Receive Adapter, (again simplistically) there are two models: Push / Pull, and in the former we typically stand up a Knative Service to handle these and for Pull based, we stand up a k8s deployment. Push based models are nice because we get autoscaling for free, whereas for Pull based we don't have a standard way to handle this (just some ideas, but this would be mosdef nice to get standard ways to do).

I'm curious to see if we can find an interface and make it pluggable enough (I'd expect however that the fact that it's only golang would be a bit too limiting). I've personally been thinking of taking a smaller step and just defining the lifecycle and by providing containers for them.

I think 2. is typically a matter of finding the right client libraries and building the container around it and stash enough information so that we can then later modify / delete the "authoritative source" it when the Source is modified / deleted. For Push Based it also needs to either stand up the data plane and wire (the authoritative source) to it. For Pull Based it stands up a Deployment.

For 3. are again typically finding the libraries and so forth. And they typically are pretty specific to the authoritative source and has a custom auth.

Anyways, just a few random thoughts and I do love the idea here. Perhaps there are two levels: LIfecycle helpers and then some golang libraries (and others?) in the form of an interface.

**Comment by vaikas-google** [comment]
Oh, and having a Standard Cloudevents Ingress which is in the works, is a great first step for the Data Plane for Push based ones, and as more and more authoritative sources emit Cloud Events the one obvious plugin to that Ingress would need to be Auth.

**Comment by alanconway** [comment]
@vaikas-google I agree with your breakdown. It is a layering problem:  to date I have focussed on the layers *inside* a process that (maybe) gets deployed in kubernetes. The "API" I'm referring to is a Go  library API, not a kubernetes API -  the  model could be expressed in any language but Go seems like a sensible starting point.

The main layer inside the process is a generic abstraction for Event, Message, Acknowledgement, Sender, Receiver, Configuration.

Transport implementations only need to implement the key abstractions (Message, Acknowlegement, Sender, Receiver)

Generic toolkit libraries can now solve common problems in a transport-neutral way: packing and unpacking messages in structured or binary form, re-coding messages in different formats or different cloud-events versions etc.

Now you can have a collection of transport plug-ins in Go, and a collection of eventing applications (source, channel, router, broker, bridge etc.)  that are maintained separately. That means you can develop a mature source application with advanced features like QoS 3 support, persistence and recovery that can speak *any* transport rather than writing a brand new, immature source application every time there's a new protocol.

Note this is all independent of the orchestration offered by knative - you can still have source implementations that don't use this toolkit, are written in other languages etc. and they will all interoperate based on the cloudEvents standard. However this toolkit would provide a much more efficient way to build a rich and mature set of sources in Go. In future we can port the abstractions to other languages once we've hashed them out in Go.

As you point out there's also a lot more to consider at the knative level and we need to make sure it all fits together.

**Comment by n3wscott** [comment]
Also, I think there could be room for more than one of these frameworks. A simple one for simple sources, a spec to implement for very complex ones, and a middle ground.

**Comment by alanconway** [comment]
> Also, I think there could be room for more than one of these frameworks. A simple one for simple sources, a spec to implement for very complex ones, and a middle ground.

The big benefit of layering is we can have both: a *transport* implementation can be as simple or complex as the transport requires, it is not itself a k8 Source  - just a library that implements Message, Sender and Receiver interfaces. 

Building a k8 Source executable is a separate exercise: the simplest source just shovels events unreliably from Receiver to a Sender. A full-featured source might support exactly-once delivery with persistent storage and message recovery. But once you've built the full-featured source you can link it with whatever transports you want, there's no need to re-write the source logic for every transport.

There could certainly be frameworks for languages other than Go that follow the same pattern.

**Comment by alanconway** [comment]
I'm currently working on the following approach - hope to have have something of POC quality for review in a few days:

Domain expert provide a cloudevents.transport.Transport implementation:
 - connects to domain, converts between domain messages and CE events. 
 - includes a JSON-unmarshallable struct for transport configuration

The framework consists of:
 - a fully functional generic eventing source with a no-op transport
 - some make/kustomize magic to blend the domain experts transport + config with the generic source and produce an independent source dedicated to the transport.

**Comment by alanconway** [comment]
Update on this work at https://github.com/alanconway/alanconway.github.io/blob/d89db2cc2d3706e735c1c77b2f1a95de9f09398c/knative/kntransport.pdf
