### ISSUE TITLE
Cloud Event model (Broker/Triggers) vs Eventing Contribs 

### ISSUE THREAD

**Issue by vpasquier** [knative/eventing-contrib#470]
## Expected Behavior

We are using on our side the Kafka contribution `KafkaSource` successfully. But our next goal was to use broker/triggers to autoscale target pods after receiving a Kafka record on a topic:

- We send a record mapping cloud event object with a given type
- The record is picked up by the Kafka Source and sent to the sink (a default broker)
- The broker forwarded it to the appropriate subscriber depending on the event type
-> It autoscales the appropriate pod depending on this type

## Actual Behavior

However the event type is always `dev.knative.kafka.event` and cannot be overriden by a custom one: therefore we cannot use triggers to filter this event cloud based on its type.

## Summary

- We'd like to know if it has been implemented on purpose (we thought that the event type was custom whatever the operator you were using to use triggers on business rules) in order to better understand the Cloud Event specs.
- Would you have another solution to use triggers with appropriate filters on cloud events? (we were thinking about having simply another topic with another KafkaSource to have a different sink... which is overkill IMHO)

Thank you so much for your time to explain to us all of this, we probably missed something.

**Comment by duglin** [comment]
IMO it is a mistake for `knative` to appear in the `type` field. The `type` value should be based on the event itself, not the Kn middleware. Consumers of events will not care that the event went thru Kn, they want what the producer sent and if the producer did not natively produce a CloudEvent, and we need to add a type, then it should be a value based on the event data, not one Kn makes up.

**Comment by duglin** [comment]
See: https://github.com/cloudevents/spec/pull/441 for examples

**Comment by grantr** [comment]
> We'd like to know if it has been implemented on purpose

No, this is a feature gap. KafkaSource doesn't yet support forwarding the CloudEvent unwrapped, but it should.

In the meantime, you can try this:
1. Create a function (Knative Service or otherwise) that receives the `dev.knative.kafka.event` event, unwraps the wrapped CloudEvent in the event body, and replies with the unpacked event. This function might be compatible with any wrapped event.
1. Create a Trigger for `dev.knative.kafka.event` events pointing to this function. Replies from the function will be fed back into the Broker.
1. Create other triggers as you expect.

**Comment by akashrv** [comment]
@n3wscott We have this concept of decorators in sources correct? Will that be helpful in this case?
@vpasquier Since the issue is open for a while without any activity, are you still blocked?
