### ISSUE TITLE
Clarify Kafka Consumer Groups needs.

### ISSUE THREAD

**Issue by vaikas** [knative/eventing-contrib#809]
As part of cleaning up the old Deprecated fields from Subscription in https://github.com/knative/eventing/pull/2335

And then figuring out if there are code that uses it, I found this:
https://github.com/knative/eventing-contrib/blob/master/kafka/channel/pkg/dispatcher/dispatcher.go#L118

And I'm having a hard time understanding if the Subscription Name/Namespace is what's important here and why. If it's that important, maybe we should not then have deprecated this from the API surface.
I do not believe there's a way to link from a UID to the actual subscription (well, in a sane way without spinning through all the subscriptions and filtering by UID), so if there's something that fundamentally needs to tie the subscription to the actual Subscription resource, we should understand it.
@matzew Since you added that fairly recently, could we figure out if there's something else that we need to surface in the type?
https://github.com/knative/eventing-contrib/commit/9639631fa788887c118692be66c7b09ae37a0a4b

**Comment by matzew** [comment]
see https://github.com/knative/eventing-contrib/pull/762 

In Kafka, when you have `n` partitions of a topic, you can have up `n` consumers for that one topic, in a (named) consumer group.

In order to have stable consumers (belonging to a consumer group), for that subscription it is important to have meaningful/stable consumer group names.

We picked the namespace and the name of the subscription, as well as the name of the channel in order to guarantee that.

```
kafka.mynamespace.mychannel.sub1
kafka.mynamespace.mychannel.sub2
```

Consumer groups ensure than that there is no "reply" of the messages from before, using UID and than (re)creating subs, is kinda randomizing that, but always having different consumergroup names, for the same subscription.

So now, it is always `kafka.mynamespace.mychannel.sub1`, instead of `kafka.123` and than `kafka.234` when recreating the sub.

This was brought up by @yuzisun recently

**Comment by vaikas** [comment]
Ok, I need to grok this little more, but it seems that there are now assumptions about naming subscriptions and especially about deleting/recreating the subscriptions that have knowledge about the implementation details of a particular channel. As in, is it correct to state that if you delete a subscription / recreate it, there's now some assumption about where the events "pick up" and start coming from?

**Comment by vaikas** [comment]
Another way to think about this is that rather than plumb the naming through and then having that control some aspects of the consumption, there could be additional information that gets passed in a more generic way if this kind of a behaviour is desired. For example (not saying we should, but...) a subscription could provide a passthrough of map[string]string that gets passed through in the subscription, that would be more generic way to plumb extra information through.

**Comment by n3wscott** [comment]
Can this solve the issue> https://github.com/knative/eventing-contrib/pull/814

**Comment by n3wscott** [comment]
Using the name of the subscription could lead to bugs because you can always delete and recreate a subscription with the same name and I think the current impl will lead to assumptions and bugs

**Comment by vaikas** [comment]
As discussed in the Channels WG meeting on 2020-01-09, we're going to merge #814 and tackle the 'how to configure underlying channel' as a more generic and clearer sematincs. In the short term if there's a need to pass information from a Subscription to Channel implementation, one can use labels. We can use this to learn what kinds of information will be necessary to pass through and we will also create an issue to track various use cases for different implementations. Today much have been driven by Kafka use cases, but we want to ensure we're not building something that only works with Kafka.
