### ISSUE TITLE
Document Sources in eventing-contrib

### ISSUE THREAD

**Issue by n3wscott** [knative/eventing-contrib#894]
From @mattmoor :

Context: I've been trying to consolidate our install docs, and something that popped out of that is trying to incorporate the stuff documented here, which includes a random subset of sources: https://knative.dev/docs/install/knative-custom-install/

Ask: Here's what I'd like to see for every source that lives in Knative in some capacity:
1. a regular release with install instructions
2. a sample that we can link from the install block (bonus: tests!)
3. for everything not satisfying the above: a feature track project board, which clearly calls out who owns it and what work is left.

/assign

**Comment by nachocano** [comment]
All of the below sources satisfy point 1 above, i.e., regular release of eventing-contrib. Some, however, do not have a sample that we can link from the install block, or the sample is outdated (e.g., old ApiVersion, CloudEvents 0.1, etc.). Can owners add/update the samples and mark it as done once merged. And include the link as well. Thanks!

- [ ] **AWS SQS**: Sample [here](https://github.com/knative/eventing-contrib/tree/master/awssqs/samples). The code still uses `sources.eventing.knative.dev`. @srvaroa can we get it migrated to `sources.knative.dev`, and the sample updated?

- [ ] **Camel**: Oudated sample [here](https://knative.dev/docs/eventing/samples/apache-camel-source/). @nicolaferraro can you update it?
- [ ] **Ceph**: Sample [here](https://github.com/knative/eventing-contrib/tree/master/ceph). @yuvalif  might be worth updating the sample to use a SinkBinding instead of a  ContainerSource, which has been deprecated. 
- [ ] **CouchDb**: Sample [here](https://github.com/knative/eventing-contrib/blob/master/couchdb/README.md). Maybe we can add a more complete example and not just the creation of the resource? @lionelvillard
- [ ] **GitHub**: Outdated sample [here](https://knative.dev/docs/eventing/samples/github-source/). @lberk, @rootfs, @bbrowning can someone update it?
- [ ] **Kafka**: Outdated sample [here](https://knative.dev/docs/eventing/samples/kafka/source/index.html). @matzew can you update it?
- [ ] **Prometheus**: Sample [here](https://github.com/knative/eventing-contrib/tree/master/prometheus). Seems quite updated! Good job @syedriko.

fyi @mattmoor

**Comment by nachocano** [comment]
@sebgoa might be worth taking a look at the new install page, and see if you can add links to TriggerMesh's documentation

**Comment by mattmoor** [comment]
@nachocano thanks for triaging these!  We should probably get each of these turned into feature tracks that talk about what it will take to carry them to GA with a clear Owner designated on the project.

For the samples that live in this repo, I think that we should try to get them into `knative/docs`?

**Comment by matzew** [comment]
@nachocano  I am not sure why the KafkaSource sample is outdated ? 
I have a related PR to update / simplify the actual install instructions for `KafakSource`... https://github.com/knative/docs/pull/2156

**Comment by matzew** [comment]
@nachocano I've told @yuvalif already about the case that the `ContainerSource` goes away in some future release. However, now that we do not yet know what the final name for `SinkBinding` is, IMO safe to wait to update, since the API is _only_ deprecated, not yet removed, AFAIK

**Comment by matzew** [comment]
@lberk @nachocano while I was at docs, I did PR an update to move the GH source forward to recently renamed `soruces.knative.dev` group

NOTE: Kafka Source is NOT yet there .....   PR will come ;-)

**Comment by nachocano** [comment]
> @nachocano I am not sure why the KafkaSource sample is outdated ?
> I have a related PR to update / simplify the actual install instructions for `KafakSource`... [knative/docs#2156](https://github.com/knative/docs/pull/2156)

My bad, I was referring to `source.knative.dev`, but just saw your other comment below... One thing though, is that I think there weren't links to the yamls, so in knative.dev you cannot run the example... Users would have to clone the repo...

**Comment by nachocano** [comment]
> @nachocano I've told @yuvalif already about the case that the `ContainerSource` goes away in some future release. However, now that we do not yet know what the final name for `SinkBinding` is, IMO safe to wait to update, since the API is _only_ deprecated, not yet removed, AFAIK

Sounds good

**Comment by nachocano** [comment]
> @nachocano thanks for triaging these! We should probably get each of these turned into feature tracks that talk about what it will take to carry them to GA with a clear Owner designated on the project.
> 
> For the samples that live in this repo, I think that we should try to get them into `knative/docs`?

Can you send me a link with some feature track template or good example that you've seen so that I can copy/paste, and update things. I can make a first pass later tonight. Thanks!
