### ISSUE TITLE
Please add support for Kafka's partition key header

### ISSUE THREAD

**Issue by FWiesner** [knative/eventing-contrib#944]
## Expected Behavior
Expectation is that 
https://github.com/cloudevents/spec/blob/master/kafka-protocol-binding.md#31-key-attribute
is supported with `KafkaChannel` (or a separated out `KafkaSink`). That way inserting messages into the Broker with a set `key` header won't lead to a `ce_key` header sent to the underlying Kafka transport, but the header will actually be named the way Kafka expects it to select a particular partition. Messages with the same key will then be enqueued in the Kafka topic on the same partition. This is a key requirement to reliably implement `event sourcing`.

## Actual Behavior
unclear, but apparently `key` gets transformed to `ce_key` and that is a key that Kafka won't interpret.

## Additional Info

**Comment by slinkydeveloper** [comment]
The spec is not clear about what the key attribute means, there is some discussion ongoing about it: https://github.com/cloudevents/spec/issues/571

**Comment by slinkydeveloper** [comment]
Ok so looking again at this after the PR on the spec for the clarification. 

Since `KafkaChannel` it's a black box Channel implementation, you **must** not rely on the fact that `KafkaChannel` respects the partition key. In other words, When you send a message to a `Channel`, you **must** not rely on what channel implementation you're actually using. If you need this particular functionality, I suggest you to create your own inbound using the sdk-go once the https://github.com/cloudevents/sdk-go/pull/437 is merged. It's actually pretty simple and we have a similar example for nats: https://github.com/cloudevents/sdk-go/blob/master/v2/cmd/samples/httptonats/main.go

**Comment by slinkydeveloper** [comment]
I'm going to close this since it's been stale for a while, feel free to reopen if you need it

/close
